# Generated by Django 4.2.7 on 2023-11-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'contacto', 'verbose_name_plural': 'contactos'},
        ),
    ]
