# Generated by Django 4.2.7 on 2023-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('servicio', models.CharField(choices=[('Social Media', 'Social Media'), ('Desarrollo Web', 'Desarrollo Web'), ('Diseño Gráfico', 'Diseño Gráfico')], max_length=50)),
            ],
        ),
    ]
